[34기 김우식] Project: Wegodang 소셜 로그인/회원가입 구현
wecode-bootcamp-korea/34-2nd-wegodang-backend pull request #6
Opened 2022-07-06 11:08 UTC by Kws1995

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 소셜 로그인/회원가입 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 소셜 로그인/회원가입 구현 - Get
- FE로부터 전달받은 카카오 access_token을 이용해 카카오 유저정보 EndPoint에 데이터를 요청
- 카카오로부터 response받은 데이터에서 필요한 정보를 객체에 담아 response
- 성공시 status 200 반환

2. 소셜 로그인/회원가입 구현 - Post
- FE로부터 kakao_id, username, email 데이터를 전달받기
- 해당 kakao_id로 가입된 데이터가 존재할 경우 프로젝트의 access_token 생성, status 200 반환
- 해당 kakao_id로 가입된 데이터가 존재하지 않을 경우 데이터를 생성하고 프로젝트의 access_token 생성, status 201 반환
- email은 유효성 검사를 진행하여 통과하지 못할 경우 ValidationError(status 400)과 에러 메세지 반환

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 외부 서버와 통신하여 데이터를 주고 받는 방법에 대해 공부해 보았습니다.
- 인증/인가에 대해서 공부해 보았습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-07-07 02:11 UTC, Kang-kyunghun requested changes

2022-07-07 02:11 UTC, Kang-kyunghun commented on wegodang/users/utils.py
> +            return JsonResponse({'message' : 'INVALID_USER'}, status=400)
인증과 관련된 status code는 401을 많이 사용합니다.

```suggestion
        except jwt.exceptions.DecodeError:
            return JsonResponse({'message' : ['INVALID_TOKEN'] }, status=401)

        except User.DoesNotExist:
            return JsonResponse({'message' : 'INVALID_USER'}, status=401)
```

2022-07-07 02:11 UTC, Kang-kyunghun commented on wegodang/users/views.py
> +        KAKAO_INFO_API = 'https://kapi.kakao.com/v2/user/me'
access_token은 보통 headers의 Authorization이라는 키로 받도로 권장하고 있습니다.
수정해 주세요.

2022-07-07 02:11 UTC, Kang-kyunghun commented on wegodang/users/views.py
> +        user_info      = requests.get(KAKAO_INFO_API, headers={'Authorization': f'Bearer {access_token}'}).json()
1. 변수명을 최대한 줄이지 말고 사용하세요.
2. requests 모듈을 사용할 때는 timeout 인자를 꼭 넣어 주셔야 합니다. 그래야 외부 요청이 잘 못 되었을 때 대응할 수 있습니다.
3. 유저 정보를 사용하기 위해 json()으로 바로 정보를 가져 왔는데, 이렇게 하면 requests로 받은 응답 값을 전부 활용하지 못 합니다. 그래서 먼저 응답을 변수에 담고 그 뒤에 body 정보나 status 정보를 활요하면 좋습니다.
4. requests를 통해 항상 올바른 응답이 오는 것은 아닙니다. 카카오로 요청 후 발생 할 수 있는 예외 상황에 대해 예외처리를 진행해 주세요.(예 권한이 없는 토큰으로 요청 했을 때)

```suggestion
        response      = requests.get(KAKAO_INFO_API, headers={'Authorization': f'Bearer {access_token}'}, timeout=5)
        user_information = response.json()
```

2022-07-07 02:11 UTC, Kang-kyunghun commented on wegodang/users/views.py
> +            return JsonResponse({"message" : "KEYERROR"}, status = 400)
단순히 except만 사용하면 모든 에러에 대해 예외처리를 진행하기 때문에 꼭 어떤 상황에 대한 예외처리인지를 나타낼 수 있어야 합니다.
```suggestion
        except KeyError:
            return JsonResponse({"message" : "KEYERROR"}, status = 400)
```

2022-07-07 02:12 UTC, Kang-kyunghun commented
postman으로 통신한 결과도 PR에 같이 첨부해 주세요.

2022-07-07 04:27 UTC, Kws1995 commented on wegodang/users/utils.py
> +            return JsonResponse({'message' : 'INVALID_USER'}, status=400)
수정했습니다 !

2022-07-07 04:43 UTC, Kws1995 commented on wegodang/users/views.py
> +        KAKAO_INFO_API = 'https://kapi.kakao.com/v2/user/me'
수정하였습니다 !

2022-07-07 04:48 UTC, Kws1995 commented on wegodang/users/views.py
> +            return JsonResponse({"message" : "KEYERROR"}, status = 400)
수정했습니다 !

2022-07-07 07:10 UTC, Kws1995 commented on wegodang/users/views.py
> +        user_info      = requests.get(KAKAO_INFO_API, headers={'Authorization': f'Bearer {access_token}'}).json()
수정했습니다 !

2022-07-07 07:22 UTC, Kws1995 commented
<img width="1035" alt="스크린샷 2022-07-07 오후 4 22 05" src="https://user-images.githubusercontent.com/104283159/177715724-2273f9a7-e531-4ec7-906d-3f36bcb9a844.png">

2022-07-07 08:20 UTC, Kang-kyunghun requested changes

2022-07-07 08:20 UTC, Kang-kyunghun commented on wegodang/users/views.py
> +            return JsonResponse({'message' : 'INVALID_RESPONSE' }, status = 400)
상태코드가 200이 아닐 때 통신 테스트 해보셨나요??
상태코드가 200이 아니면, 유저 정보를 가져올 수가 없어서 위의 코드에서 키에러가 발생합니다. 
그러면 우식님이 의도하신 예외처리가 정상적으로 작동하지 않게 됩니다.

따라서 해당 코드의 위치가 변경 되어야 하는데, 변경 위치는 한 번 고민해 보시고 수정해 주세요.

2022-07-07 09:43 UTC, Kws1995 commented on wegodang/users/views.py
> +            return JsonResponse({'message' : 'INVALID_RESPONSE' }, status = 400)
수정해보았습니다...!

2022-07-08 01:12 UTC, Kang-kyunghun requested changes
test code 추가해 주세요.

2022-07-08 01:12 UTC, Kang-kyunghun commented on wegodang/users/views.py
> +        return JsonResponse({'message': 'LOG_IN_SUCCESS', 'token': client_token}, status=200)
해당 코드와 위의 KakaoSignup의 post와 차이가 무엇인가요? 코멘트로 남겨주세요

2022-07-08 06:01 UTC, Kws1995 commented on wegodang/users/views.py
> +        return JsonResponse({'message': 'LOG_IN_SUCCESS', 'token': client_token}, status=200)
피드백 받은대로 수정하였습니다 !

2022-07-08 06:19 UTC, Kang-kyunghun requested changes
수정 사항 한 번 반영해 주시고 unit test 올려주세요.

2022-07-08 06:19 UTC, Kang-kyunghun commented on wegodang/users/views.py
> +            is_user = True
User.objects.filter(kakao_id = kakao_id).exists():의 결과 자체가 boolean이기 때문에 if는 필요 없을 것 같습니다.
```suggestion
        is_user          = User.objects.filter(kakao_id = kakao_id).exists():

```

2022-07-08 06:30 UTC, Kws1995 commented on wegodang/users/views.py
> +            is_user = True
코드 수정하였습니다 !

2022-07-12 01:17 UTC, Kang-kyunghun requested changes

2022-07-12 01:17 UTC, Kang-kyunghun commented on wegodang/users/validator.py
> +    if not EMAIL_REGEX:
사소 할 수 있지만, 구문 사이에 공백 추가해 주세요.
```suggestion
    EMAIL_REGEX = re.match('^[a-zA-z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9.]+$', email)
    
    
    if not EMAIL_REGEX:
```
```suggestion
    EMAIL_REGEX = re.match('^[a-zA-z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9.]+$', email)
    if not EMAIL_REGEX:
```

2022-07-12 01:17 UTC, Kang-kyunghun commented on wegodang/users/tests.py
> +        self.assertEqual(response.status_code, 201|200)
1. 상태코드를 201 또는 200 둘다 하셨는데, 해당 코드가 나오는 상황을 정확히 판단 하셔야 합니다.
200과 201에 대한 상황을 정확히 분리해 주세요.
2. 로그인이 성공 할 때 말고 실패 했을 때(예외처리)에 대해서도 테스트 추가해 주세요.(최소 1개)

2022-07-12 01:17 UTC, Kang-kyunghun commented on wegodang/users/views.py
> +        is_user = User.objects.filter(kakao_id = kakao_id).exists()
```suggestion
        is_user          =User.objects.filter(kakao_id = kakao_id).exists()
```

2022-07-12 06:33 UTC, Kws1995 commented on wegodang/users/validator.py
> +    if not EMAIL_REGEX:
수정하였습니다 !

2022-07-12 06:33 UTC, Kws1995 commented on wegodang/users/tests.py
> +        self.assertEqual(response.status_code, 201|200)
추가 유닛 테스트 작성하였습니다 !

2022-07-12 06:33 UTC, Kws1995 commented on wegodang/users/views.py
> +        is_user = User.objects.filter(kakao_id = kakao_id).exists()
수정하였습니다 !

2022-07-12 09:06 UTC, Kang-kyunghun commented
고생하셨습니다!

2022-07-12 09:06 UTC, merged